# Description:
#   Bazel workspace file for twim.

workspace(name = "ru_eustas_twim_c")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "zlib",
    url = "https://github.com/madler/zlib/archive/v1.2.11.tar.gz",
    sha256 = "629380c90a77b964d896ed37163f5c3a34f6e6d897311f1df2a7016355c45eff",
    build_file_content = """
cc_library(
    name = "zlib",
    defines = ["HAVE_UNISTD_H"],
    srcs = [
        "adler32.c",
        "compress.c",
        "crc32.c",
        "crc32.h",
        "deflate.c",
        "deflate.h",
        "gzclose.c",
        "gzguts.h",
        "gzlib.c",
        "gzread.c",
        "gzwrite.c",
        "infback.c",
        "inffast.c",
        "inffast.h",
        "inffixed.h",
        "inflate.c",
        "inflate.h",
        "inftrees.c",
        "inftrees.h",
        "trees.c",
        "trees.h",
        "uncompr.c",
        "zconf.h",
        "zutil.c",
        "zutil.h",
    ],
    hdrs = ["zlib.h"],
    includes = ["."],
    visibility = ["//visibility:public"],
)
    """,
    strip_prefix = "zlib-1.2.11",
)

http_archive(
    name = "png",
    url = "https://github.com/glennrp/libpng/archive/v1.6.37.tar.gz",
    sha256 = "ca74a0dace179a8422187671aee97dd3892b53e168627145271cad5b5ac81307",
    build_file_content = """
genrule(
    name = "pnglibconf",
    srcs = ["scripts/pnglibconf.h.prebuilt"],
    outs = ["pnglibconf.h"],
    cmd = "cp -f $< $@",
)

cc_library(
    name = "png",
    srcs = [
        "png.c",
        "pngconf.h",
        "pngdebug.h",
        "pngerror.c",
        "pngget.c",
        "pnginfo.h",
        ":pnglibconf",
        "pngmem.c",
        "pngpread.c",
        "pngpriv.h",
        "pngread.c",
        "pngrio.c",
        "pngrtran.c",
        "pngrutil.c",
        "pngset.c",
        "pngstruct.h",
        "pngtrans.c",
        "pngwio.c",
        "pngwrite.c",
        "pngwtran.c",
        "pngwutil.c",
    ],
    hdrs = ["png.h"],
    includes = ["."],
    linkopts = ["-lm"],
    visibility = ["//visibility:public"],
    deps = ["@zlib//:zlib"],
)
    """,
    strip_prefix = "libpng-1.6.37",
)

http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/refs/tags/release-1.11.0.zip",
    sha256 = "353571c2440176ded91c2de6d6cd88ddd41401d14692ec1f99e35d013feda55a",
    strip_prefix = "googletest-release-1.11.0",
)

http_archive(
    name = "hwy",
    url = "https://github.com/google/highway/archive/8e5750125c02fb75a348cdc02382758f763bcd06.zip",
    sha256 = "2d17ef44a5aa5fc935b0584c88146e37a01720295a76f19a025307c2c0535011",
    strip_prefix = "highway-8e5750125c02fb75a348cdc02382758f763bcd06",
)

# TODO(eustas): looks like bazel bug - no reson to include this project here.
http_archive(
    name = "bazel_skylib",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.3/bazel-skylib-1.0.3.tar.gz",
    ],
    sha256 = "1c531376ac7e5a180e0237938a2536de0c54d93f5c278634818e0efc952dd56c",
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()
