name: Build / test C project with CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          export BUILD_DIR=${RUNNER_TEMP}/build
          cmake -B ${BUILD_DIR} ${GITHUB_WORKSPACE}/c/
          cmake --build ${BUILD_DIR}
