name: Build / test JS project with Bazel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}/js/
          bazel build ...:all
      - name: Test
        run: |
          cd ${GITHUB_WORKSPACE}/js/
          bazel test --test_output=errors ...:all
      - name: Clean
        run: |
          cd ${GITHUB_WORKSPACE}/js/
          bazel clean
