name: Build / test WASM project with CMake
on: [workflow_dispatch]
jobs:
  make-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
      - uses: actions/checkout@v2
      - name: Set Environment Variables
        run: |
          echo "ARTIFACTS_DIR=${RUNNER_TEMP}/artifacts" >> ${GITHUB_ENV}
      - uses: actions/download-artifact@v2
        with:
          name: wasm
          path: ${{ env.ARTIFACTS_DIR }}
