name: Build / test WASM project with CMake
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.23
          actions-cache-folder: 'emsdk-cache'
      - name: Cache Binaryen
        id: cache-binaryen
        uses: actions/cache@v2
        with:
          path: binaryen
          key: binaryen
      - name: Download Binaryen
        if: steps.cache-binaryen.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/binaryen
          cd ${GITHUB_WORKSPACE}/binaryen
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz | tar -xz --strip-components=1
      - name: Set Environment
        run: |
          echo "SCALAR_BUILD_DIR=${GITHUB_WORKSPACE}/build-scalar" >> ${GITHUB_ENV}
          echo "SIMD_BUILD_DIR=${GITHUB_WORKSPACE}/build-simd" >> ${GITHUB_ENV}
          echo "ARTIFACTS_DIR=${GITHUB_WORKSPACE}/artifacts" >> ${GITHUB_ENV}
      - name: Build Scalar
        run: |
          cd ${GITHUB_WORKSPACE}/
          export PATH=${PATH}:${GITHUB_WORKSPACE}/binaryen/bin
          export BUILD_DIR=${SCALAR_BUILD_DIR}
          emcmake cmake -B ${BUILD_DIR} -D CMAKE_BUILD_TYPE=Release ./c/
          cmake --build ${BUILD_DIR}
      - name: Build SIMD
        run: |
          cd ${GITHUB_WORKSPACE}/
          export PATH=${PATH}:${GITHUB_WORKSPACE}/binaryen/bin
          export BUILD_DIR=${SIMD_BUILD_DIR}
          emcmake cmake -B ${BUILD_DIR} -D CMAKE_BUILD_TYPE=Release -D TWIM_WASM_ENABLE_SIMD=ON ./c/
          cmake --build ${BUILD_DIR}
      - name: Collect Artifacts
        run: |
          mkdir -p ${ARTIFACTS_DIR}/
          cp ${SCALAR_BUILD_DIR}/twim.wasm ${ARTIFACTS_DIR}/
          cp ${SIMD_BUILD_DIR}/simd-twim.wasm ${ARTIFACTS_DIR}/
      - uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: ${{ARTIFACTS_DIR}}
          if-no-files-found: error
