name: Build / test WASM project with CMake / update node modules
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "SCALAR_BUILD_DIR=${RUNNER_TEMP}/build-scalar" >> ${GITHUB_ENV}
          echo "SIMD_BUILD_DIR=${RUNNER_TEMP}/build-simd" >> ${GITHUB_ENV}
          echo "ARTIFACTS_DIR=${RUNNER_TEMP}/artifacts" >> ${GITHUB_ENV}
          echo "BINARYEN_DIR=${RUNNER_TEMP}/binaryen" >> ${GITHUB_ENV}
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.23
          actions-cache-folder: 'emsdk-cache'
      - name: Cache Binaryen
        id: cache-binaryen
        uses: actions/cache@v2
        with:
          path: ${{ env.BINARYEN_DIR }}
          key: binaryen
      - name: Download Binaryen
        if: steps.cache-binaryen.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${BINARYEN_DIR}
          cd ${BINARYEN_DIR}
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_101/binaryen-version_101-x86_64-linux.tar.gz | tar -xz --strip-components=1
      - name: Build Scalar
        run: |
          export PATH=${PATH}:${BINARYEN_DIR}/bin
          export BUILD_DIR=${SCALAR_BUILD_DIR}
          emcmake cmake -B ${BUILD_DIR} -D CMAKE_BUILD_TYPE=Release ${GITHUB_WORKSPACE}/c/
          cmake --build ${BUILD_DIR}
      - name: Build SIMD
        run: |
          export PATH=${PATH}:${BINARYEN_DIR}/bin
          export BUILD_DIR=${SIMD_BUILD_DIR}
          emcmake cmake -B ${BUILD_DIR} -D CMAKE_BUILD_TYPE=Release -D TWIM_WASM_ENABLE_SIMD=ON ${GITHUB_WORKSPACE}/c/
          cmake --build ${BUILD_DIR}
      - name: Collect Artifacts
        run: |
          mkdir -p ${ARTIFACTS_DIR}/
          cp ${SCALAR_BUILD_DIR}/twim.wasm ${ARTIFACTS_DIR}/
          cp ${SIMD_BUILD_DIR}/simd-twim.wasm ${ARTIFACTS_DIR}/
      - uses: actions/upload-artifact@v2
        with:
          name: wasm
          path: ${{ env.ARTIFACTS_DIR }}
          if-no-files-found: error
      - name: Update  node modules
        run: |
          echo "${GITHUB_EVENT_NAME}"
  update:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ env.github_event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: wasm
